### PR TITLE
add 2.6.1 for python 3.6 support

### PR DESCRIPTION
**Pull request by a358003542**
Please make sure it can works for your machine, I have test in mine.

1. add 2.6.1 for python 3.6 support
2. update readme for how to build the wheel

### CODE REVIEW

**Comment by sfbahr** [comment]
I'll go ahead and merge this after I test it on my machine. In general I don't think people should be using PyCrypto though since it's dead. I've just updated the readme to say as such.

Edit: Decided against this, see below

**Comment by memclutter** [comment]
Please, merge this, and add for Python 3.7.1.

**Comment by sfbahr** [comment]
I'm inclined to not add this since PyCrypto is dead

**Comment by a358003542** [comment]
agreed

**Pull request closed without merging**
